CREATE SMALLFILE TABLESPACE "TBS1_BASE01" 
DATAFILE '/u01/app/oracle/oradata/ORCL1/datafile/tbs1_base01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE 1G 
BLOCKSIZE 8K
LOGGING ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;