-- Consulta
SELECT FILE_NAME, TABLESPACE_NAME,
STATUS, ONLINE_STATUS, BYTES/1024/1024 AS TAMANHO_MB
FROM DBA_DATA_FILES WHERE TABLESPACE_NAME =
'TBS1_BASE01' ;

-- Comando
ALTER DATABASE DATAFILE
'/u01/app/oracle/oradata/ORCL1/datafile/tbs1_base01.dbf' RESIZE 200M;