SELECT * FROM DBA_TABLESPACES;
SELECT * FROM V$TABLESPACE;
SELECT * FROM DBA_TABLESPACE_USAGE_METRICS;
SELECT * FROM DBA_DATA_FILES;
SELECT * FROM V$DATAFILE_HEADER;
SELECT * FROM DBA_TEMP_FILES;
SELECT * FROM DBA_TABLESPACE_GROUPS;
SELECT * FROM V$ENCRYPTED_TABLESPACES;
SELECT * FROM ALL_VIEWS WHERE VIEW_NAME LIKE 'DBA%';
SELECT * FROM V$PARAMETER WHERE NAME =
'db_create_file_dest'; -- Local padrão de armazenamento dos datafiles